# Shared configuration for all services

spring:
  jackson:
    date-format: dd/MM/yyyy HH:mm:ss
    time-zone: Asia/Ho_Chi_Minh
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
  datasource:
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      pool-name: HyperMallHikariPool
      max-lifetime: 1800000
      connection-timeout: 30000
  jpa:
    hibernate:
        ddl-auto: ${JPA_DDL_AUTO:none}
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

# JWT Configuration
app:
  jwt:
    secret: ${JWT_SECRET}
    access-token-expiration: 900000
    refresh-token-expiration: 604800000

# Eureka Client
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
  client:
    registry-fetch-interval-seconds: 10
    service-url:
      defaultZone: ${EUREKA_URI:http://${EUREKA_USERNAME}:${EUREKA_PASSWORD}@localhost:8761/eureka/}

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when_authorized

# Logging
logging:
  level:
    com.hypermall: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
