server:
  port: ${USER_SERVICE_PORT:8081}

spring:
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/hypermall_user?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

# Email configuration
app:
  mail:
    from: ${MAIL_FROM:noreply@hypermall.com}
    verification-link: ${MAIL_VERIFICATION_LINK:http://localhost:3000/verify-email}
    reset-password-link: ${MAIL_RESET_PASSWORD_LINK:http://localhost:3000/reset-password}
