spring:
  security:
    user:
      name: ${CONFIG_USERNAME:config}
      password: ${CONFIG_PASSWORD:config123}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://${EUREKA_USERNAME:eureka}:${EUREKA_PASSWORD:eureka123}@localhost:8761/eureka/}
